config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get 'discover', to: 'frontend#discover' 

  get 'diving', to: 'frontend#diving' 

  get 'fishing', to: 'frontend#fishing'

  get 'kiteboarding', to: 'frontend#kiteboarding'

  get ':section/reservation/:code/:accomodation', to: 'frontend#reservation'

  post 'reserve', to: 'reservations#create' 

  get 'price_activity/:name', to: 'reservations#price_activity' 

  devise_for :users, skip: KepplerConfiguration.skip_module_devise

  mount KepplerCatalogs::Engine, :at => '/', as: 'catalogs'

  resources :admin, only: :index

  scope :admin do   

    resources :rooms do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end 

  	resources :users do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :quotes do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :activities do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end

    resources :packages do 
      resources :offers do
        get '(page/:page)', action: :index, on: :collection, as: ''
        delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
      end
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end 

    resources :reservations, except: :create do 
      get '/charge', to: 'reservations#create_charge'
      get '/cancel', to: 'reservations#cancel_charge'
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end   

    resources :customers do 
      get '(page/:page)', action: :index, on: :collection, as: ''
      delete '/destroy_multiple', action: :destroy_multiple, on: :collection, as: :destroy_multiple
    end 
  end


  #errors
  match '/403', to: 'errors#not_authorized', via: :all, as: :not_authorized
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #dashboard
  mount KepplerGaDashboard::Engine, :at => '/', as: 'dashboard'


end

app/models/activity.rb
#Generado por keppler
require 'elasticsearch/model'
class Activity < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  has_many :reservation_customer_activities, :dependent => :destroy
  has_many :customers, :dependent => :destroy
  validates_presence_of :name, :price

  after_commit on: [:update] do
    puts __elasticsearch__.index_document
  end
  
  def self.searching(query)
    if query
      self.search(self.query query).records.order(id: :desc)
    else
      self.order(id: :desc)
    end
  end

  def self.query(query)
    { query: { multi_match:  { query: query, fields: [] , operator: :and }  }, sort: { id: "desc" }, size: self.count }
  end

  #armar indexado de elasticserch
  def as_indexed_json(options={})
    {
      id: self.id.to_s,
      name:  self.name.to_s,
      description:  self.description.to_s,
      price:  self.price.to_s,
    }.as_json
  end

end
#Activity.import

app/controllers/activities_controller.rb
#Generado con Keppler.
class ActivitiesController < ApplicationController  
  before_filter :authenticate_user!
  layout 'admin/application'
  load_and_authorize_resource
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  # GET /activities
  def index
    activities = Activity.searching(@query).all
    @objects, @total = activities.page(@current_page), activities.size
    redirect_to activities_path(page: @current_page.to_i.pred, search: @query) if !@objects.first_page? and @objects.size.zero?
  end

  # GET /activities/1
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to activities_path, notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /activities/1
  def update
    if @activity.update(activity_params)
      redirect_to activities_path, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  def destroy_multiple
    Activity.destroy redefine_ids(params[:multiple_ids])
    redirect_to activities_path(page: @current_page, search: @query), notice: "Usuarios eliminados satisfactoriamente" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def activity_params
      params.require(:activity).permit(:name, :description, :price)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_description.html.haml
.listing-show-header
	%h5
		= material_icon.md_24.add_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	.list
		%h5 Descripcion del modulo
		%p{align: "justify"} Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non	proident, sunt in culpa qui officia deserunt mollit anim id est laborum..

app/views/activities/_form.html.haml
.wrapper
	.wrapper-body.container
		.actions
			= link_to activities_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark")
		.wrapper-inputs
			.card
				= simple_form_for @activity do |f|
					.row
						= f.input :name						
						= f.input :description, input_html: { class: "materialize-textarea" }
						= f.input :price

						.form-actions.right
							= f.button :submit, "Guardar", class: "btn"

app/views/activities/_index_show.html.haml
.listing-show-header
	.actions
		- if can? :update, Activity
			= link_to edit_activity_path(@activity), class: "btn-floating waves-effect waves-light btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
				= material_icon.md_24.create
	%h5
		= material_icon.md_24.add_circle.css_class("md-light") 
		= t("model.singular.#{controller_name.singularize}")
.listing-show-body.card{ resize: true , style: "height: {{windowHeight}}px;" }
	%ul.list
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.name")
			.display-value= @activity.name
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.description")
			.display-value= @activity.description
		%li.list-row
			.display-label= t("model.#{controller_name.singularize}.attributes.price")
			.display-value= "$#{@activity.price}"
	

:javascript
	$(".modal-trigger").leanModal();
	$('.tooltipped').tooltip({delay: 1});

app/views/activities/_listing.html.haml
%tr{ id: "row-#{activity.id}" }
	- if can? :destroy_multiple, Activity
		%td.item-check{style:"width: 10%"}
			= link_to "", activity_path(activity), remote: true, class: "show-row"
			%input{ type:"checkbox", class: "filled-in", id: "checkbox-#{activity.id}", 'checklist-model'=>"check", 'checklist-value'=>"#{activity.id}", "ng-click"=>"selectByCheck(#{@objects.size})"}
			%label{ for: "checkbox-#{activity.id}" }

		%td{style:"width: 50%"}
			= link_to "", activity_path(activity, search: @query), remote: true, class: "show-row"
			%span
				= activity.name
		%td{style:"width: 30%"}
			= link_to "", activity_path(activity, search: @query), remote: true, class: "show-row"
			%span
				= "$#{activity.price}"
								
	%td{style:"width: 5%"}		
		= link_to activity_path(activity), class: "btn-floating waves-effect btn-flat" do
			= material_icon.md_24.more_horiz.css_class("md-dark")

app/views/activities/edit.html.haml
= title "Activities - editar | #{@activity.id}"
= render 'form'

app/views/activities/index.html.haml
= title("Activities - Listado")
.listing.col.l9.m12.s12
	- if can? :new, model
		= link_to new_activity_path, class: "btn-floating btn-large waves-effect waves-light teal btn-new hide-on-small-only" do
			= material_icon.md_24.add
	= entries(@total, @objects)
	%table.bordered
		%tbody
			- @objects.each do |activity|
				= render 'listing', activity: activity
			- if @objects.size.zero?
				%tr
					%td{colspan: "4"}
						%center
							No se han encontrado activities.
	= paginate @objects, window: 1

.listing-show.col.l3.m12.hide-on-small-and-down.hide-on-med-and-down
	= render "description"

- if can? :new, model
	= link_to new_activity_path, class: "btn-index-add btn-floating btn-large teal waves-effect waves-light red" do
		= material_icon.md_24.add.css_class("md-light")

app/views/activities/new.html.haml
= title "Activities - Nuevo"
= render 'form'

app/views/activities/show.html.haml
= title "Activities | #{@activity.id}"
.wrapper
	.wrapper-body.container
		.actions
			- if can? :delete, Activity
				= link_to activity_path(@activity), class: "btn-floating btn-flat right tooltipped", "data-position" => "bottom", "data-tooltip" => "Eliminar", method: :delete, data: { confirm: 'Are you sure?' } do
					= material_icon.md_18.delete.css_class("md-dark")	
			- if can? :update, Activity
				= link_to edit_activity_path(@activity), class: "right btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Editar" do
					= material_icon.md_18.create.css_class("md-dark")
			= link_to activities_path, class: "btn-floating btn-flat tooltipped", "data-position" => "bottom", "data-tooltip" => "Volver" do
				= material_icon.md_18.arrow_back.css_class("md-dark") 
		.card			
			%ul.list
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.name")
					.display-value.fs-body-1.tc-black-2= @activity.name.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.description")
					.display-value.fs-body-1.tc-black-2= @activity.description.to_s.humanize
				%li.list-row
					.display-label= t("model.#{controller_name.singularize}.attributes.price")
					.display-value.fs-body-1.tc-black-2= "$#{@activity.price}"

app/views/activities/show.js.haml
$(".listing-show").html("#{j render('index_show')}")
$('.listing table').find(".active").removeClass("active")
$("#row-#{@activity.id}").addClass("active")
$scope = angular.element($(".listing-show")).scope()
$scope.compiledHTML($(".listing-show"))
$(".listing-show-body").trigger("click");